export PORT=3010
export TOKEN_SECRET=O_Filme_Senhor_dos_Anéis_é_Ruim
export MONGO_DB_CONNECTION=mongodb://cliniksDB:aSITFA8SFAIULSBFASIGFAS87@mongo:27020/?authSource=cliniksDB
export MONGO_GATEWAYPAG_CONNECTION=mongodb://gatewayPag:aSITFA8SFAIULSBFASIGFAS87@mongo:27021/?authSource=gatewayPag
export MONGO_LOGISTICS_CONNECTION=mongodb://logistics:aSITFA8SFAIULSBFASIGFAS87@mongo:27022/?authSource=logistics
export MONGO_CHATDB_CONNECTION=mongodb://chatDB:aSITFA8SFAIULSBFASIGFAS87@mongo:27023/?authSource=chatDB
export MONGO_NOTIFY_CONNECTION=mongodb://notifyDB:aSITFA8SFAIULSBFASIGFAS87@mongo:27024/?authSource=notifyDB
export INITIAL_IMAGE=https://caderninho-images.s3.sa-east-1.amazonaws.com/avatar.png
export INITIAL_PRODUCT_IMAGE=https://caderninho-images.s3.sa-east-1.amazonaws.com/product.jpg
export AWS_BUCKET_NAME=caderninho-images
export AWS_BUCKET_REGION=sa-east-1
export AWS_ACCESS_KEY=AKIATMBPR735WDX2HYGI
export AWS_PRIVATE_KEY=T4MBXTwRBgFt83jZhNg+FYnCVKttLuGntmQA3z+A
export CLINIKS_APPTOKEN=OWRQ8rileuqe2o9fo23FO9FWPFU9W1ofuO2FB23OFU
export REDIS_HOST=localhost
export REDIS_PORT=6379
export REDIS_PASS=1kg1i34g1o2i34g1lii23g4
export MAIL_SENDER_PROVIDER=Hotmail
export MAIL_SENDER_USER=valgusto2000@hotmail.com
export MAIL_SENDER_PASSWORD=Vas12591!
export MAIL_SENDER=valgusto2000@hotmail.com